/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OverridesRouteImport } from './routes/overrides'
import { Route as ConfigFilesRouteImport } from './routes/config-files'
import { Route as IndexRouteImport } from './routes/index'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OverridesRoute = OverridesRouteImport.update({
  id: '/overrides',
  path: '/overrides',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigFilesRoute = ConfigFilesRouteImport.update({
  id: '/config-files',
  path: '/config-files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config-files': typeof ConfigFilesRoute
  '/overrides': typeof OverridesRoute
  '/overview': typeof OverviewRoute
  '/plugins': typeof PluginsRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config-files': typeof ConfigFilesRoute
  '/overrides': typeof OverridesRoute
  '/overview': typeof OverviewRoute
  '/plugins': typeof PluginsRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config-files': typeof ConfigFilesRoute
  '/overrides': typeof OverridesRoute
  '/overview': typeof OverviewRoute
  '/plugins': typeof PluginsRoute
  '/rules': typeof RulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/config-files' | '/overrides' | '/overview' | '/plugins' | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config-files' | '/overrides' | '/overview' | '/plugins' | '/rules'
  id:
    | '__root__'
    | '/'
    | '/config-files'
    | '/overrides'
    | '/overview'
    | '/plugins'
    | '/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigFilesRoute: typeof ConfigFilesRoute
  OverridesRoute: typeof OverridesRoute
  OverviewRoute: typeof OverviewRoute
  PluginsRoute: typeof PluginsRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overrides': {
      id: '/overrides'
      path: '/overrides'
      fullPath: '/overrides'
      preLoaderRoute: typeof OverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-files': {
      id: '/config-files'
      path: '/config-files'
      fullPath: '/config-files'
      preLoaderRoute: typeof ConfigFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigFilesRoute: ConfigFilesRoute,
  OverridesRoute: OverridesRoute,
  OverviewRoute: OverviewRoute,
  PluginsRoute: PluginsRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
